### PR TITLE
174105084 history

### PR DESCRIPTION
**Pull request by Raytray**
Adds audit. It's not the cleanest implementation so looking for feedback on how to best do it.

Some things that I know are problems that I need to address but unsure about are..
- [x] Why is ```@revisions``` content automatically rendered before the tbody
- [ ] Fetch Revision information only when modal is opened.
- [x] Make history table body relevant. (Only track things showing up there, or give a way to show all possible changes)

The blob of text above is the representation of the revision data, not sure why it's rendering. :(
image

### CODE REVIEW

**Comment by MatthewSchultz** [comment]
I'll look at this asap.

**Comment by Raytray** [comment]
I switched it from revisions to audits which makes more sense for what we want to display.

image

Need to make it more user friendly/readable though. Maybe filter to only fields we want to see here.

**Comment by Raytray** [comment]
image

New problem, need a way to get the reference data to show meaningful history value changes of updates.

**Comment by MatthewSchultz** [comment]
It's not perfect, and it still needs some work, but there's enough here to start thinking about merging.

**Pull request merged**
